"""アプリ全体で使用する定数."""

# ロール（§11, §18）
ROLE_LEADER = "LEADER"
ROLE_CHECKER = "CHECKER"
ROLE_CLEANER = "CLEANER"
ROLE_CODES = (ROLE_LEADER, ROLE_CHECKER, ROLE_CLEANER)

# 希望種別（§12）
PREFERENCE_UNAVAILABLE = "UNAVAILABLE"
PREFERENCE_PREFER_OFF = "PREFER_OFF"
PREFERENCE_PREFER_WORK = "PREFER_WORK"
PREFERENCE_TYPES = (
    PREFERENCE_UNAVAILABLE,
    PREFERENCE_PREFER_OFF,
    PREFERENCE_PREFER_WORK,
)

# 月間シフトの状態（§25）
SCHEDULE_STATUS_DRAFT = "DRAFT"
SCHEDULE_STATUS_CONFIRMED = "CONFIRMED"
SCHEDULE_STATUS = (SCHEDULE_STATUS_DRAFT, SCHEDULE_STATUS_CONFIRMED)

# 勤務割当の作成元（§26）
SOURCE_OPTIMIZED = "OPTIMIZED"
SOURCE_MANUAL = "MANUAL"
SOURCE_TYPES = (SOURCE_OPTIMIZED, SOURCE_MANUAL)

# Solver設定（§38）: 時間制限は4 Stage合計の上限
TOTAL_SOLVE_TIME_LIMIT_SECONDS = 10.0
SOLVER_RANDOM_SEED = 42
SOLVER_NUM_WORKERS = 1
